apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: gopinathchkspipelines 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gopinathchkspipelines 
    spec:
      containers:
        - name: gopinathchkspipelines 
          image: sh360demo.azurecr.io/gopinathchkspipelines 
          ports:
          - containerPort: 3000